title: "Dr. Vishwanath Bijalwan"
email: "vishwanathbijalwan@ieee.org"
description: >- 
  Assistant Professor | DAAD AI-NET Fellow | AI, Robotics, Biomedical Signal Processing
baseurl: ""
url: "https://vishwanathbijalwan.github.io"
github_username: vishwanathbijalwan

markdown: kramdown
theme: minimal-mistakes-jekyll
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Social
author:
  name: "Dr. Vishwanath Bijalwan"
  avatar: "/assets/images/profile.jpg"
  bio: "AI | Robotics | Signal Processing"
  links:
    - label: "Google Scholar"
      url: "https://scholar.google.com/citations?user=9hp9lw0AAAAJ&hl=en"
    - label: "LinkedIn"
      url: "https://www.linkedin.com/in/dr-vishwanath-bijalwan-0a692236/"
    - label: "ResearchGate"
      url: "https://www.researchgate.net/profile/Vishwanath-Bijalwan"
    - label: "ORCID"
      url: "https://orcid.org/0000-0002-8661-5430"
    - label: "GitHub"
      url: "https://github.com/vishwanathbijalwan"
