title: "Dr. Vishwanath Bijalwan"
description: "AI | Robotics | Biomedical Signal Processing"
theme: minima
markdown: kramdown
url: "https://vishwanathbijalwan.github.io"
baseurl: ""

author:
  name: "Dr. Vishwanath Bijalwan"
  avatar: "/assets/images/profile.jpg"
  email: vishwanathbijalwan@ieee.org
  links:
    - label: "Google Scholar"
      url: "https://scholar.google.com/citations?user=9hp9lw0AAAAJ&hl=en"
    - label: "LinkedIn"
      url: "https://www.linkedin.com/in/dr-vishwanath-bijalwan-0a692236/"
    - label: "ORCID"
      url: "https://orcid.org/0000-0002-8661-5430"
    - label: "ResearchGate"
      url: "https://www.researchgate.net/profile/Vishwanath-Bijalwan"
